CREATE OR REPLACE DATABASE DYNAMICTRANSACTIONSPROCESSINGSYSTEM;
CREATE OR REPLACE USER dtpsapp@localhost IDENTIFIED BY 'dtpsapp123';
GRANT ALL PRIVILEGES ON DYNAMICTRANSACTIONSPROCESSINGSYSTEM.* TO dtpsapp@localhost;
FLUSH PRIVILEGES;
USE DYNAMICTRANSACTIONSPROCESSINGSYSTEM;

