CREATE DATABASE dtps;
CREATE USER dtpsapp WITH PASSWORD 'dtpsapp123';
ALTER DATABASE dtps OWNER TO dtpsapp;

CREATE TABLE IF NOT EXISTS Job_Status(
    id INT PRIMARY KEY,
    name VARCHAR(15) NOT NULL
);

